# 14. Plot Euclidean vs Manhattan distance contours and explain geometric differences between K-Means and K-Median.
import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(-5,5,200)
y=np.linspace(-5,5,200)
X,Y=np.meshgrid(x,y)
euclidean=np.sqrt(X**2+Y**2)
manhattan=np.abs(X)+np.abs(Y)
plt.figure()
plt.contour(X,Y,euclidean)
plt.title("Euclidean Distance Contours")
plt.xlabel("X")
plt.ylabel("Y")
plt.gca().set_aspect('equal', 'box')
plt.show()
plt.figure()
plt.contour(X,Y,manhattan)
plt.title("Manhattan Distance Contours")
plt.xlabel("X")
plt.ylabel("Y")
plt.gca().set_aspect('equal', 'box')
plt.show()
print("Euclidean contours are circular showing spherical geometry used in KMeans.")
print("Manhattan contours are diamond shaped showing axis aligned geometry used in KMedian.")
print("Raja Kumar Sah, 23053769")